_BASE_: "Base.yaml"
SOLVER:
  TYPE: "sgd"
  IMS_PER_BATCH: 4
  BASE_LR: 0.000625
  STEPS: (3340800, 4454400)
  MAX_ITER: 5568000
  WARMUP_ITERS: 174000
TEST:
  EVAL_PERIOD: 1000
VIS_PERIOD: 111360
OUTPUT_DIR: "output/behave_example_run_finetune"
DATASETS:
  TRAIN: ('Behave_Train',)
  TEST: ('Behave_Test',) 
  CATEGORY_NAMES: ('backpack', 'basketball', 'boxlarge', 'boxlong', 'boxmedium','boxsmall', 'boxtiny', 'chairblack','chairwood', 'keyboard', 'monitor', 'plasticcontainer', 'stool', 'suitcase', 'tablesmall', 'tablesquare', 'toolbox', 'trashbin', 'yogaball', 'yogamat')
MODEL:
  WEIGHTS: "checkpoints/cubercnn_DLA34_FPN.pth"
  ROI_HEADS:
    NUM_CLASSES: 20